version: '3.8'

services:
  rofl-decryptor:
    build: .
    image: "https://hub.docker.com/r/wa1terbish0p/decryptor"
    platform: linux/amd64  
    ports:
      - "3000:3000"
    environment:
      - RPC_URL=${RPC_URL}
      - PRIVATE_KEY=${PRIVATE_KEY}
      - CONTRACT_ADDRESS=${CONTRACT_ADDRESS}
    restart: unless-stopped
